%$RAML 0.8
title: Panella Add REST POints
version: 0.1
baseUri: http://localhost/
mediaType: application/json
documentation:
  - title:  Penella Add and Bulk ADD API
    content: |
      This documentation describes the API for inserting a Triple and bulk inserting Triples
      into Penella

schemas:
  - Add: !include schemas/Add.json

/{name}:
  description: A named database
  uriParamters:
    name:
      type: string
      description: The name of the database to access
  /_add:
    description: Add a triple to specified DB
    body:
