%$RAML 0.8
title: Panella Add REST Points
version: 0.1Alpha
baseUri: http://localhost/
mediaType: application/json
documentation:
  - title:  Penella REST API
    content: |
      This documentation describes the API for creating databases and adding and querying databases.

schemas:
  - add_database: !include schemas.add.database.schema.json

/_add/{name}:
    description: Create a new database
    uriParameters:
        name: string
        description: Name of the DB to create
    post:
        description: Adds a new DB into the cluster
        body:
            application/json:
                schema: add_database
                eample: !include examples/add.database.example.json
